name: myblog_ui
description: Provide UI that relies on myblog-api.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.0.0
  myblog_proto_dart:
    git:
      url: https://github.com/nomkhonwaan/myblog-proto-dart
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter

